# Brief Summary of Processed Files
The purpose of this file is to summarize some of the processed files (i.e., dataframes) by reading their first few rows, to give a sense how the processed data look like. 
For data privacy concerns, not all the dataframes may be shown.

In [4]:
import pandas as pd

### Filter loading master

df = pd.read_excel(r'filter_loading_master.xlsx')
df.drop('lat', axis = 1, inplace = True) 
df.iloc[:, :-2].head()

,ft,td,ExpN,M_filter_blank,Petridish_w_dust_m,Petridish_wo_dust_m,Pre_hepa_sampler_m,Post_hepa_sampler_m,M_filter_pre,Dust_sprinkled_m,Filter_m_change,Flow_dust_m,Lost_dust_m,Mass_closure
0,1,1,20,271.541,5.90481,3.36336,19.60687,19.98540,272.701,2.54145,1.160,0.37853,1.00292,60.537488
1,1,2,21,255.647,5.82050,3.29629,19.62185,19.76872,257.433,2.52421,1.786,0.14687,0.59134,76.573265
2,2,1,16,257.932,5.84839,3.29064,19.96907,20.48762,259.109,2.55775,1.177,0.51855,0.86220,66.290685
3,2,1,11,260.785,5.34718,3.36078,36.79977,37.02013,261.591,1.98640,0.806,0.22036,0.96004,51.669352
4,2,2,17,256.740,5.85997,3.29161,19.88609,20.17685,258.178,2.56836,1.438,0.29076,0.83960,67.309879

In [19]:
### Artificially loaded filter recovery data (cycle by cycle)

df = pd.read_excel(r'artl_dataset_summary.xlsx')
print("Columns of this dataframe are: {}".format(list(df.columns[:-1])))
df.iloc[:, :-1].head()

Columns of this dataframe are: ['ExpN', 'Cycle_N', 'ft', 'td', 'M_filter_post', 'M_filter_change', 'M_filter_change_cum', 'M_d', 'M_d_cum', 'M_s', 'M_s_cum', 'E', 'E_cum', 'C', 'D', 'CE', 'CE_cum', 'M_C', 'M_C_cum', 'dustmass', 'Mass_C', 'M_t', 'M_t_cum', 'sCE', 'sCE_cum', 'tCE', 'tCE_cum', 'd_t_rat', 'd_t_rat_cum']

,ExpN,Cycle_N,ft,td,M_filter_post,M_filter_change,M_filter_change_cum,M_d,M_d_cum,M_s,...,dustmass,Mass_C,M_t,M_t_cum,sCE,sCE_cum,tCE,tCE_cum,d_t_rat,d_t_rat_cum
0,1,1,3,2,272.921,2.133,2.133,1.38413,1.38413,0.28598,...,14.829,NaN,1.67011,1.67011,1.928518,1.928518,11.262459,11.262459,0.828766,0.828766
1,2,1,3,2,288.762,1.526,1.526,0.60291,0.60291,0.09923,...,3.558,1.50926,0.70214,0.70214,2.788926,2.788926,19.734120,19.734120,0.858675,0.858675
2,2,2,3,2,288.246,0.516,2.042,0.19414,0.79705,0.01518,...,3.558,0.24995,0.20932,0.91146,0.426644,3.215571,5.883080,25.617201,0.927479,0.874476
3,3,1,3,1,286.370,1.306,1.306,0.52961,0.52961,0.00043,...,3.269,0.60903,0.53004,0.53004,0.013154,0.013154,16.214133,16.214133,0.999189,0.999189
4,3,2,3,1,286.220,0.150,1.456,0.06705,0.59666,-0.00059,...,3.269,0.09228,0.06646,0.59650,-0.018048,-0.004894,2.033038,18.247170,1.008878,1.000268

In [12]:
### Artificially loaded filter recovery data (aggregated cumulative over all cycles of extraction over the same filters)

df = pd.read_excel(r'artl_dataset_summary_collapsed.xlsx')
df.head()

,ExpN,Cycle_N,M_d_cum,M_s_cum,M_t_cum,CE_cum,sCE_cum,tCE_cum,d_t_rat_cum,ft,td,dustmass,M_filter_change_cum
0,1,1,1.38413,0.28598,1.67011,9.333940,1.928518,11.262459,0.828766,3,2,14.829,2.133
1,2,2,0.79705,0.11441,0.91146,22.401630,3.215571,25.617201,0.874476,3,2,3.558,2.042
2,3,2,0.59666,0.00043,0.59650,18.252065,0.013154,18.247170,1.000268,3,1,3.269,1.456
3,4,2,0.71150,0.05578,0.76728,19.824464,1.554193,21.378657,0.986569,3,2,3.589,1.764
4,5,2,1.81261,0.05400,1.86661,50.730758,1.511335,52.242093,0.971136,3,2,3.573,2.400

In [29]:
### PSD of measured samples (volume fractions over 92 bins)

df = pd.read_excel(r'artl_v_psd_master.xlsx')
df.iloc[12:25,[0] + list(range(25, 38))]
# Only a subset of columns shown. 
# Other processed files such as "artl_c_psd_master.xlsx", "artl_v_psd_master_sieve.xlsx", and "artl_psd_sieve.xlsx" have similar structures (not shown).

,Size,Eval_020_iso2_08m_fg_180406_am_count,Eval_020_iso2_08m_hd_180406_am_count,Eval_020_iso2_08m_fg_180406_am_mean,Eval_020_iso2_08m_hd_180406_am_mean,Eval_020_iso2_08m_fg_180406_am_median,Eval_020_iso2_08m_hd_180406_am_median,Eval_020_iso2_08m_fg_180406_am_min,Eval_020_iso2_08m_hd_180406_am_min,Eval_020_iso2_08m_fg_180406_am_max,Eval_020_iso2_08m_hd_180406_am_max,Eval_020_iso2_08m_fg_180406_am_std,Eval_020_iso2_08m_hd_180406_am_std,Eval_019_ash2_14e_hd_180405_am_count
12,0.398,5,5,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,5
13,0.447,5,5,0.000,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,5
14,0.501,5,5,0.050,0.000,0.05,0.00,0.05,0.00,0.05,0.00,0.000000,0.000000,5
15,0.562,5,5,0.170,0.090,0.17,0.09,0.17,0.09,0.17,0.09,0.000000,0.000000,5
16,0.631,5,5,0.344,0.244,0.34,0.24,0.34,0.24,0.35,0.25,0.005477,0.005477,5
17,0.708,5,5,0.524,0.396,0.52,0.40,0.52,0.39,0.53,0.40,0.005477,0.005477,5
18,0.794,5,5,0.670,0.536,0.67,0.54,0.66,0.53,0.68,0.54,0.007071,0.005477,5
19,0.891,5,5,0.756,0.626,0.76,0.63,0.75,0.62,0.76,0.63,0.005477,0.005477,5
20,1.000,5,5,0.772,0.662,0.77,0.66,0.77,0.65,0.78,0.67,0.004472,0.008367,5
21,1.120,5,5,0.808,0.710,0.81,0.71,0.80,0.70,0.81,0.72,0.004472,0.010000,5
22,1.260,5,5,0.788,0.706,0.79,0.71,0.78,0.70,0.79,0.71,0.004472,0.005477,5
23,1.410,5,5,0.836,0.760,0.84,0.76,0.83,0.75,0.84,0.77,0.005477,0.010000,5
24,1.580,5,5,0.938,0.864,0.94,0.86,0.93,0.86,0.94,0.87,0.004472,0.005477,5

In [32]:
### PSD modal analysis results from all tests
# Modes 1 - 6 descriptions are in the following table (see below).
# Letters f and v in column names refer to fraction and volume.

df = pd.read_excel(r'psd_modal_analysis_summary.xlsx')
df

,expn,td,ft,mode_1_v,mode_2_v,mode_3_v,mode_1_f,mode_2_f,mode_3_f,mode_4_v,mode_5_v,mode_6_v,mode_4_f,mode_5_f,mode_6_f
0,3,1,3,0.2500,8.50,4.000,0.019608,0.666667,0.313725,NaN,NaN,NaN,NaN,NaN,NaN
1,6,1,3,0.1000,5.00,7.000,0.008264,0.413223,0.578512,NaN,NaN,NaN,NaN,NaN,NaN
2,7,1,3,0.1000,4.50,7.600,0.008197,0.368852,0.622951,NaN,NaN,NaN,NaN,NaN,NaN
3,10,1,3,0.2000,7.00,5.000,0.016393,0.573770,0.409836,NaN,NaN,NaN,NaN,NaN,NaN
4,11,1,2,0.1000,3.50,7.500,0.009009,0.315315,0.675676,NaN,NaN,NaN,NaN,NaN,NaN
5,12,1,3,0.1500,5.50,6.000,0.012876,0.472103,0.515021,NaN,NaN,NaN,NaN,NaN,NaN
6,13,1,3,0.1800,7.00,4.900,0.014901,0.579470,0.405629,NaN,NaN,NaN,NaN,NaN,NaN
7,14,1,3,0.1800,6.50,5.500,0.014778,0.533662,0.451560,NaN,NaN,NaN,NaN,NaN,NaN
8,16,1,2,0.1500,7.30,4.500,0.012552,0.610879,0.376569,NaN,NaN,NaN,NaN,NaN,NaN
9,18,1,4,0.2500,6.00,5.700,0.020921,0.502092,0.476987,NaN,NaN,NaN,NaN,NaN,NaN
10,20,1,1,0.1200,3.50,7.800,0.010508,0.306480,0.683012,NaN,NaN,NaN,NaN,NaN,NaN
11,50,1,0,0.2500,7.80,3.500,0.021645,0.675325,0.303030,NaN,NaN,NaN,NaN,NaN,NaN
12,1,2,3,0.2000,6.24,2.800,0.017331,0.540728,0.242634,1.4,0.4,0.5,0.121317,0.034662,0.043328
13,2,2,3,0.1500,3.50,5.500,0.012448,0.290456,0.456432,0.3,1.0,1.6,0.024896,0.082988,0.132780
14,4,2,3,0.1580,4.00,4.000,0.013789,0.349101,0.349101,2.0,0.8,0.5,0.174551,0.069820,0.043638
15,5,2,3,0.1800,6.50,2.800,0.015679,0.566202,0.243902,1.3,0.7,0.0,0.113240,0.060976,0.000000
16,9,2,3,0.0800,1.80,5.800,0.006734,0.151515,0.488215,0.4,1.5,2.3,0.033670,0.126263,0.193603
17,15,2,3,0.1500,4.80,4.500,0.013100,0.419214,0.393013,1.0,1.0,0.0,0.087336,0.087336,0.000000
18,17,2,2,0.1000,4.00,5.000,0.008333,0.333333,0.416667,0.5,0.9,1.5,0.041667,0.075000,0.125000
19,19,2,4,0.1000,4.00,5.000,0.008547,0.341880,0.427350,0.8,0.7,1.1,0.068376,0.059829,0.094017
20,21,2,1,0.1500,4.30,5.300,0.012766,0.365957,0.451064,0.2,0.6,1.2,0.017021,0.051064,0.102128
21,51,2,0,0.1875,5.85,2.625,0.016358,0.510360,0.229008,0.8,0.7,1.3,0.069793,0.061069,0.113413

Mode information is listed in the following table:

| Mode #|GM (Micron)|GSD (-)|
|-------|-----------|-------|
|   1   |    0.9    |  1.2  |
|   2   |    4.3    |  2.5  |
|   3   |    32.0   |  2.0  |
|   4   |    20.0   |  1.5  |
|   5   |   150.0   |  2.0  |
|   6   |   550.0   |  1.6  |

In [35]:
### PSD of all samples calculated from modal analysis
# Test dust is indicated by ash or iso in the column names.
# filter type is indicated by 08m, 08e, 11e, and 14e for the recovered sample (original test dust samples does not have filter type but indicated by 00a).
# the three digits after "fit_" are the experiment numbers.

df = pd.read_excel(r'C:\Career\Learning\Python Practice\Stata_Python_Booster\PhD - Extraction\Processed\artificial\modal\modal_combine_all.xlsx')
df.head(10)

,Size,fit_001_11e_ash,fit_002_11e_ash,fit_003_11e_iso,fit_004_11e_ash,fit_005_11e_ash,fit_006_11e_iso,fit_007_11e_iso,fit_009_11e_ash,fit_010_11e_iso,...,fit_014_11e_iso,fit_015_11e_ash,fit_016_08e_iso,fit_017_08e_ash,fit_018_14e_iso,fit_019_14e_ash,fit_020_08m_iso,fit_021_08m_ash,fit_050_00a_iso,fit_051_00a_ash
0,0.100,0.000596,0.000334,0.000812,0.000382,0.000621,0.000478,0.000430,0.000172,0.000669,...,0.000621,0.000459,0.000697,0.000382,0.000573,0.000382,0.000334,0.000411,0.000745,0.000559
1,0.112,0.000983,0.000551,0.001339,0.000630,0.001024,0.000788,0.000709,0.000284,0.001103,...,0.001024,0.000756,0.001150,0.000630,0.000945,0.000630,0.000551,0.000677,0.001229,0.000921
2,0.126,0.001626,0.000912,0.002215,0.001042,0.001694,0.001303,0.001173,0.000469,0.001824,...,0.001694,0.001251,0.001902,0.001042,0.001564,0.001042,0.000912,0.001121,0.002033,0.001525
3,0.141,0.002590,0.001453,0.003528,0.001660,0.002698,0.002075,0.001868,0.000747,0.002905,...,0.002698,0.001992,0.003030,0.001660,0.002490,0.001660,0.001453,0.001785,0.003237,0.002428
4,0.158,0.004085,0.002291,0.005564,0.002619,0.004255,0.003273,0.002946,0.001178,0.004582,...,0.004255,0.003142,0.004779,0.002619,0.003928,0.002619,0.002291,0.002815,0.005106,0.003830
5,0.178,0.006474,0.003631,0.008819,0.004150,0.006744,0.005188,0.004669,0.001868,0.007263,...,0.006744,0.004980,0.007574,0.004150,0.006225,0.004150,0.003631,0.004462,0.008093,0.006070
6,0.200,0.009992,0.005604,0.013611,0.006405,0.010408,0.008006,0.007206,0.002882,0.011209,...,0.010408,0.007686,0.011689,0.006405,0.009608,0.006405,0.005604,0.006885,0.012490,0.009367
7,0.224,0.015003,0.008415,0.020437,0.009617,0.015628,0.012022,0.010820,0.004328,0.016830,...,0.015628,0.011541,0.017552,0.009617,0.014426,0.009617,0.008415,0.010339,0.018754,0.014065
8,0.251,0.022222,0.012464,0.030270,0.014245,0.023147,0.017806,0.016025,0.006410,0.024928,...,0.023147,0.017094,0.025996,0.014245,0.021367,0.014245,0.012464,0.015313,0.027777,0.020833
9,0.282,0.032689,0.018335,0.044528,0.020954,0.034051,0.026193,0.023574,0.009429,0.036670,...,0.034051,0.025145,0.038242,0.020954,0.031432,0.020954,0.018335,0.022526,0.040861,0.030646

In [36]:
### P-values from Kolmogorov-Smirnov tests comparing PSD of test and recovered dust

df = pd.read_excel(r'k_s_all.xlsx')
df.head(10)

   ExpN        P Value
0     1   0.000000e+00
1     2   0.000000e+00
2     3  3.578658e-187
3     4   0.000000e+00
4     5   0.000000e+00
5     6   0.000000e+00
6     7   0.000000e+00
7     9   0.000000e+00
8    10  2.109750e-194
9    11   0.000000e+00

In [37]:
### P-values from Shapiro-Wilk normality tests to verify log-normality of the PSDs from the test and recovered dust

df = pd.read_excel(r's_w_p_values_all.xlsx')
df.head(10)

  Unnamed: 0      p_values
0     021_hd  1.574785e-08
1     020_hd  1.260481e-15
2     019_hd  6.716518e-09
3     018_hd  4.503530e-14
4     017_hd  1.050564e-09

End of Code